peft_config:
  type: tied_lora
  r: 128
  premult: false
  postmult: true
  alpha: 806.5063506110791
  gamma: 1050.9246567675123
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 7.584587697148255e-06
weight_decay: 0.001
