peft_config:
  type: normed_lora
  r: 8
  alpha: 175.00518624771794
  gamma: 600.2558486310709
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 3.0011659812680063e-05
weight_decay: 0.001
