peft_config:
  type: strong_gamma_lora
  r: 8
  alpha: 365.0374678653286
  gamma: 2565.734316834799
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 3.0511255580364225e-06
weight_decay: 0.001
