peft_config:
  type: normed_lora
  r: 8
  alpha: 36.184987435129614
  gamma: 3.171208974866611
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 2.7607403853801605e-05
weight_decay: 0.001
