peft_config:
  type: tied_lora_extra
  a: 8
  b: 8
  premult: false
  postmult: false
  alpha: 100.0
  gamma: 750.0
model_name: meta-llama/Llama-3.1-8B
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 3.0e-05
weight_decay: 0.001
