peft_config:
  type: strong_gamma_lora
  r: 8
  alpha: 2.9999999999999982
  gamma: 182.57418583505543
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 2.9999999999999977e-05
weight_decay: 0.001
