peft_config:
  type: dora
  r: 8
  transpose: false
  eps: 1.0e-06
  alpha: 360.8293447211655
  gamma: 4.3053526110391225
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 6.6393989234326804e-06
weight_decay: 0.001
