peft_config:
  type: lora
  r: 8
  alpha: 0.7752757471584714
  gamma: 7.709827911646318
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 3.0e-05
weight_decay: 0.001
