peft_config:
  type: dora
  r: 8
  transpose: false
  eps: 1.0e-06
  alpha: 124.81811703805553
  gamma: 706.4102945191671
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 2.906558988394797e-05
weight_decay: 0.001
