peft_config:
  type: partially_tied_lora
  r: 32
  la: 4
  lb: 4
  premult: false
  midmult: false
  postmult: false
  alpha: 121.27282710168731
  gamma: 818.3127246481471
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 2.9994721702615785e-05
weight_decay: 0.001
