peft_config:
  type: strong_gamma_lora
  r: 8
  alpha: 3.6692966676192436
  gamma: 21.11534442254061
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 0.0003035391380788668
weight_decay: 0.001
