peft_config:
  type: normed_lora
  r: 8
  alpha: 8.849981839239069
  gamma: 9.857489999565013
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 0.00012603778571180157
weight_decay: 0.001
