peft_config:
  type: normed_lora
  r: 8
  alpha: 72.09840805587316
  gamma: 2638.376661983651
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 6.6916804527615144e-06
weight_decay: 0.001
