peft_config:
  type: tied_lora
  r: 128
  premult: false
  postmult: true
  alpha: 407.8466962911455
  gamma: 880.8844276226698
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 7.563979654194396e-06
weight_decay: 0.001
