peft_config:
  type: normed_lora
  r: 8
  alpha: 332.01199646536855
  gamma: 966.880615205203
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 1.7830518072552584e-05
weight_decay: 0.001
