peft_config:
  type: dora
  r: 8
  transpose: false
  eps: 1.0e-06
  alpha: 110.30074624123647
  gamma: 762.8938624769092
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 3.178608195847001e-05
weight_decay: 0.001
