peft_config:
  type: normed_lora
  r: 8
  alpha: 5.470626166736722
  gamma: 4.643241504580765
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 5.336974611316779e-05
weight_decay: 0.001
