peft_config:
  type: normed_lora
  r: 8
  alpha: 478.70006197855116
  gamma: 1628.141371147239
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 1.97241402859533e-05
weight_decay: 0.001
