peft_config:
  type: normed_lora
  r: 8
  alpha: 44.83579286001053
  gamma: 91.32046019575756
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 0.0002708574888050544
weight_decay: 0.001
