peft_config:
  type: normed_lora
  r: 8
  alpha: 8.343583314191854
  gamma: 701.1201537593973
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 3.54860001396388e-05
weight_decay: 0.001
