peft_config:
  type: normed_lora
  r: 8
  alpha: 3.911866569895032
  gamma: 1.5524491045005706
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 7.229736737660341e-06
weight_decay: 0.001
