peft_config:
  type: simple_dora
  r: 8
  transpose: false
  eps: 1.0e-06
  alpha: 44.26584696247162
  beta: 1.0
  gamma: 1045.2003564001586
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 2.5223207239953512e-05
weight_decay: 0.001
