peft_config:
  type: normed_lora
  r: 8
  alpha: 10.196178634395508
  gamma: 114.89346510028909
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 1.9689076422292367e-05
weight_decay: 0.001
