peft_config:
  type: simple_dora
  r: 4
  transpose: false
  eps: 1.0e-06
  alpha: 330.0
  beta: 1.0
  gamma: 960.0
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 1.787e-05
weight_decay: 0.001
