peft_config:
  type: dora
  r: 8
  transpose: false
  eps: 1.0e-06
  alpha: 59.79691194383379
  gamma: 318.2908359360922
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 0.0001730411365472459
weight_decay: 0.001
