peft_config:
  type: normed_lora
  r: 8
  alpha: 26.178243039599046
  gamma: 322.8248363638001
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 5.914376646815619e-06
weight_decay: 0.001
