peft_config:
  type: normed_lora
  r: 8
  alpha: 100.71535866947445
  gamma: 1017.0078125778925
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 2.044947103692999e-05
weight_decay: 0.001
