peft_config:
  type: normed_lora
  r: 8
  alpha: 969.0139565815181
  gamma: 6.799825470287877
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 3.0e-05
weight_decay: 0.001
