peft_config:
  type: strong_gamma_lora
  r: 8
  alpha: 112.41171901582499
  gamma: 3.5271467465958968
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 3.0e-05
weight_decay: 0.001
