peft_config:
  type: partially_tied_lora
  r: 32
  la: 4
  lb: 4
  premult: false
  midmult: false
  postmult: false
  alpha: 121.97997481267785
  gamma: 779.8456115355763
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 2.9998203227000535e-05
weight_decay: 0.001
