peft_config:
  type: normed_lora
  r: 8
  alpha: 695.2298587167375
  gamma: 219.8384197903378
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 4.325774631490735e-06
weight_decay: 0.001
