peft_config:
  type: normed_lora
  r: 8
  alpha: 486.1990694992302
  gamma: 1690.6711198633316
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 2.1681977221899373e-05
weight_decay: 0.001
