peft_config:
  type: normed_lora
  r: 8
  alpha: 327.911081660486
  gamma: 948.0896953439662
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 1.7937662412953585e-05
weight_decay: 0.001
