peft_config:
  type: tied_lora
  r: 128
  premult: false
  postmult: true
  alpha: 826.0825647530288
  gamma: 910.7186683747987
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 4.664963180656557e-06
weight_decay: 0.001
