peft_config:
  type: normed_lora
  r: 8
  alpha: 3.0890773745030415
  gamma: 1306.2660324813182
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 5.507157674086656e-06
weight_decay: 0.001
