peft_config:
  type: normed_lora
  r: 8
  alpha: 318.32839502877914
  gamma: 926.0190703671761
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 1.8247895141263613e-05
weight_decay: 0.001
