peft_config:
  type: tied_lora
  r: 128
  premult: false
  postmult: true
  alpha: 42.345422032152065
  gamma: 238.44687328263623
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 0.0001525028603978091
weight_decay: 0.001
