peft_config:
  type: partially_tied_lora
  r: 32
  la: 4
  lb: 4
  premult: false
  midmult: false
  postmult: false
  alpha: 100.00000000000004
  gamma: 182.57418583505543
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 2.9999999999999977e-05
weight_decay: 0.001
