peft_config:
  type: normed_lora
  r: 8
  alpha: 5.768636643774825
  gamma: 1133.1021854308954
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 6.212675453208461e-06
weight_decay: 0.001
