peft_config:
  type: normed_lora
  r: 8
  alpha: 102.66121244355536
  gamma: 935.7259840718062
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 2.576015495678269e-05
weight_decay: 0.001
