peft_config:
  type: normed_lora
  r: 8
  alpha: 152.7137663992566
  gamma: 1307.6328307475871
model_name: google/gemma-2b
dataset_randomize: false
seq_len: 463
out_dir: data
epochs: 3
batchsize: 1
seed: 0
logging_steps: 250
peak_learning_rate: 1.7652903516088853e-05
weight_decay: 0.001
